import assert from 'node:assert/strict';
import { candidateApprovalPath } from '../apps/web/src/candidate-links.ts';
import { candidateDecision, INITIAL_SETTINGS, readMarketRiskView } from '../packages/domain/src/index.ts';
import { orderValidationFixture } from './support/order-market-fixture.mjs';
const candidate = { id: 'candidate/with space', nextAction: {kind:'approval',label:'Review',target:'supplier_contact'} } as const;
assert.equal(candidateApprovalPath(candidate), '/candidates/candidate%2Fwith%20space/contact');
assert.equal(candidateApprovalPath({...candidate,nextAction:{...candidate.nextAction,target:'order_decision'}}), '/candidates/candidate%2Fwith%20space/orders');
assert.equal(candidateApprovalPath({...candidate,nextAction:{...candidate.nextAction,kind:'waiting'}}), null);
assert.equal(candidateApprovalPath({...candidate,nextAction:{...candidate.nextAction,kind:'automatic'}}), null);
assert.equal(candidateApprovalPath({...candidate,nextAction:{...candidate.nextAction,target:'unrecognized'}}), null);
const passing = orderValidationFixture(INITIAL_SETTINGS);
const passingMarket = readMarketRiskView(passing);
assert.equal(candidateDecision({phase:'api_validation',status:'pass',marketRisk:passingMarket,settings:INITIAL_SETTINGS}),'go');
const caution = orderValidationFixture(INITIAL_SETTINGS,'caution');
assert.equal(candidateDecision({phase:'api_validation',status:'pass',marketRisk:readMarketRiskView(caution),settings:INITIAL_SETTINGS}),'caution');
assert.equal(candidateDecision({phase:'screening',status:'reject',marketRisk:null,settings:null}),'no_go');
assert.equal(candidateDecision({phase:'api_validation',status:'hold',marketRisk:null,settings:INITIAL_SETTINGS}),'waiting');
console.log('PASS: approval links and candidate GO, CAUTION, NO-GO, WAITING decisions are mapped without exposing unsupported actions.');
